// faryal Hakim's record as an example1
const patientrecord1 = [{
    "zzAbstractLink": 78990,
    "CoderNumberDesc": "Faryal Hakim",
    "ChartNumber": "KEYER0096",
    "RegistrationNumber": "096",
    "DispositionDate": "2023-08-30T00:00:00.000Z",
    "DispositionTime": "1900-01-01T11:43:00.000Z",
    "DispositionTimeUnknown": null,
    "InstitutionNumberDesc": "ST. LAWRENCE COLLEGE Ambulatory Care",
    "LastName": "Kirk",
    "FirstName": "Paula",
    "GenderDesc": "Female",
    "BirthDate": "1947-06-06T00:00:00.000Z",
    "ResponsiblityForPayment": "07",
    "PostalCode": "K7K2P8",
    "ArrivalModeDesc": "WALK IN",
    "ArrivalDate": "2023-08-30T00:00:00.000Z",
    "ArrivalTime": "1900-01-01T08:29:00.000Z",
    "InstitutionFromDesc": null,
    "MISCodeDesc": "General Emergency",
    "ContactModeDesc": "Visit (Face-To-Face) With Individual Client/Family At Facility",
    "AdmitbyAmbulanceDesc": "No Ambulance",
    "AmbulanceArrivalDate": null,
    "AmbulanceArrivalTime": null,
    "AmbulanceArrivalTimeUnknown": null,
    "AmbulanceTransferCareDate": null,
    "AmbulanceTransferCareTime": null,
    "AmbulanceTransferCareTimeUnknown": null,
    "ReferredFromDesc": "Self/Family",
    "TriageLevelDesc": "Urgent",
    "TriageDate": "2023-08-30T00:00:00.000Z",
    "TriageTime": "1900-01-01T08:31:00.000Z",
    "TriageTimeUnknown": null,
    "AssessmentDate": "2023-08-30T00:00:00.000Z",
    "AssessmentTime": "1900-01-01T10:49:00.000Z",
    "AssessmentTimeUnknown": null,
    "DateLeftER": "2023-08-30T00:00:00.000Z",
    "TimeLeftER": "1900-01-01T11:43:00.000Z",
    "TimeLeftERUnknown": null,
    "DischargeDispositionDesc": "Discharge to private home, condo, apt without support service/referral",
    "ReferredToDesc": "Ambulatory Care Service (Facility Based)",
    "InstitutionToDesc": null,
    "ConsultOccurrence": null,
    "Consultnumberdesc": null,
    "ConsultServiceDesc": null,
    "ConsultRequestDate": null,
    "ConsultRequestTime": null,
    "ConsultArrivalTimeUnknown": null,
    "ConsultArrivalDate": null,
    "ConsultArrivalTime": null,
    "ProviderOccurrence": 1,
    "ProviderNumber": "0015",
    "ProviderSpecialtyDesc": "Emergency Medicine",
    "ProviderTypeDesc": "Most Responsible",
    "DiagnosisOccurrence": 2,
    "diagnosisprefix": null,
    "diagnosiscode": "B96.1  ",
    "diagnosissuffix": null,
    "diagnosistype": null,
    "InterventionOccurrence": null,
    "InterventionDate": null,
    "InterventionCode": null,
    "InterventionSuffixDesc": null,
    "InterventionAttributeStatus": null,
    "InterventionAttributeLocation": null,
    "InterventionAttributeExtent": null,
    "InterventionProviderNumberDesc": null,
    "InterventionProviderSpecialty": null,
    "IntervDateIn": null,
    "InterventionTimeIn": null,
    "IntervDateOut": null,
    "InterventionTimeOut": null,
    "InterventionLocation": null,
    "AnesthetistIDDesc": null,
    "AnestheticTechniqueDesc": null
}]
